image: python:3.10.5


variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

stages:
  - publish

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .cache/pip
    - .venv

.with_poetry:
  before_script:
    - pip install poetry
    - poetry --version
    - poetry config virtualenvs.in-project true
    - poetry install

license_dump:
  extends: .with_poetry
  stage: publish
  script:
    - poetry run pip-licenses --from=mixed --order=license --with-system --format=csv  > licenses.csv
  artifacts:
    paths:
      - licenses.csv
    expire_in: 1 week

publish:
  extends: .with_poetry
  stage: publish
  rules:
    - if: '$CI_COMMIT_TAG != null'
  script:
    - poetry config repositories.gitlab https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry config http-basic.gitlab gitlab-ci-token ${CI_JOB_TOKEN}
    - poetry build
    - poetry publish -r gitlab

