import os

CONFIDENCE_CHUNK_SIZE = int(os.getenv(
    'MOKAPOT_CONFIDENCE_CHUNK_SIZE')) or 1000000
CHUNK_SIZE_READ_ALL_DATA = int(os.getenv(
    'MOKAPOT_CHUNK_SIZE_READ_ALL_DATA')) or 200000
CHUNK_SIZE_ROWS_PREDICTION = int(os.getenv(
    'MOKAPOT_CHUNK_SIZE_ROWS_PREDICTION')) or 700000
CHUNK_SIZE_COLUMNS_FOR_DROP_COLUMNS = int(os.getenv(
    'MOKAPOT_CHUNK_SIZE_COLUMNS_FOR_DROP_COLUMNS')) or 19
CHUNK_SIZE_ROWS_FOR_DROP_COLUMNS = int(os.getenv(
    'MOKAPOT_CHUNK_SIZE_ROWS_FOR_DROP_COLUMNS')) or 2000000
