#name: PyPI
#
#on:
#  release:
#    types: [created]
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v3
#    - name: Set up Python
#      uses: actions/setup-python@v4
#      with:
#        python-version: '3.10'
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install setuptools wheel twine build
#    - name: Build and publish
#      env:
#        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#      run: |
#        python -m build --sdist --wheel .
#        twine upload dist/*

name: Publish to Github

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install uv
      run: |
        pip install uv
    - name: Build and publish
      env:
        UV_PUBLISH_USERNAME: __token__
        UV_PUBLISH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        UV_PUBLISH_URL: https://python.pkg.github.com/${{ github.repository_owner }}
      run: |
        uv build --no-sources
        uv publish